/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logins;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author UNDERTAKER
 */
public class Login_s extends javax.swing.JFrame {

    /**
     * Creates new form Login_s
     */
    public Login_s() {
        initComponents();
         this.setExtendedState(MAXIMIZED_BOTH);
         show_user();
    }


    public ArrayList<User>userList(){ 
    
    ArrayList<User>usersList = new ArrayList<>();
    try{ 
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        
          
          Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1444;databaseName=DB1;user=TestingUser;password=root");
          String query1="Select *from tbl2";
          Statement st= con.createStatement();
          ResultSet rs= st.executeQuery(query1);
          User user;
          while(rs.next()){ 
          
          user= new User(rs.getString("Name"),rs.getString("Address"),rs.getInt("Post_Code"),rs.getInt("Telephone"),rs.getInt("NID"),rs.getString("Email"));
          usersList.add(user);
          
          }
          
                  
          
          
         
         
         
        }catch(Exception e){ 
          JOptionPane.showMessageDialog(null,e);
        
        }
        return usersList;
    
    }
    
    public void show_user(){ 
    
    ArrayList<User> list = userList();
    
    DefaultTableModel model = (DefaultTableModel)jTable_Display_User.getModel();
    
    Object[]row=new Object[6];
    
    for(int i=0;i<list.size();i++){ 
    row[0]=list.get(i).getNID();
    row[1]=list.get(i).getName();
    row[2]=list.get(i).getAddress();
    row[3]=list.get(i).getPost_Code();
    row[4]=list.get(i).getTelephone();
    row[5]=list.get(i).getEmail();
    model.addRow(row);
    
    }
    
    
    
    }
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nid = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        pc = new javax.swing.JTextField();
        tele = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display_User = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        deleteBTn = new javax.swing.JButton();
        np = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(450, 400));

        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 600));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("NID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Address");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Post Code");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Telephone");

        saveBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(0, 102, 0));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        jTable_Display_User.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NID", "Name", "Address", "Post Code", "Telephone", "Email"
            }
        ));
        jTable_Display_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Display_UserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Display_User);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Enter Your Information Here");

        updateBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(0, 102, 0));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBTn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteBTn.setForeground(new java.awt.Color(204, 0, 0));
        deleteBTn.setText("Delete");
        deleteBTn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTnActionPerformed(evt);
            }
        });

        np.setBackground(new java.awt.Color(51, 51, 255));
        np.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        np.setText("Next");
        np.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                npActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Email");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(saveBtn)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel7)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nid)
                                    .addComponent(name)
                                    .addComponent(address)
                                    .addComponent(pc)
                                    .addComponent(tele, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(email)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(updateBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(deleteBTn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(np, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(pc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveBtn)
                            .addComponent(updateBtn)
                            .addComponent(deleteBTn))
                        .addGap(34, 34, 34)
                        .addComponent(np, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed

        // TODO add your handling code here:
        
      
            String id = nid.getText();
        String na= name.getText();
        String ad=address.getText();
        String post = pc.getText();
        String te = tele.getText();
       String em = email.getText();
          try{ 
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        
          
          Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1444;databaseName=DB1;user=TestingUser;password=root");
          
          Statement st= con.createStatement();
          
          st.executeUpdate("insert into Tbl2 values("+id+",'"+na+"','"+ad+"',"+post+","+te+",'"+em+"')");
          
          DefaultTableModel model=(DefaultTableModel)jTable_Display_User.getModel();
          
          model.setRowCount(0);
          
          show_user();
          
          
          JOptionPane.showMessageDialog(this, "Data saved");
          
         
         
         
        }catch(Exception e){ 
          JOptionPane.showMessageDialog(null,e);
        
        }
        
        
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void jTable_Display_UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Display_UserMouseClicked
        // TODO add your handling code here:
        
        int i=jTable_Display_User.getSelectedRow();
        TableModel model =jTable_Display_User.getModel();
        nid.setText(model.getValueAt(i, 0).toString());
        name.setText(model.getValueAt(i, 1).toString());
        address.setText(model.getValueAt(i, 2).toString());
        pc.setText(model.getValueAt(i, 3).toString());
        tele.setText(model.getValueAt(i, 4).toString());
        email.setText(model.getValueAt(i, 5).toString());
    }//GEN-LAST:event_jTable_Display_UserMouseClicked

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        String id =nid.getText();
        String na= name.getText();
        String ad=address.getText();
        String post = pc.getText();
        String te = tele.getText();
        String em=email.getText();
        
        
          try{ 
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        
          
          Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1444;databaseName=DB1;user=TestingUser;password=root");
          
          int row =jTable_Display_User.getSelectedRow();
          
          String value=(jTable_Display_User.getModel().getValueAt(row, 0).toString());
          Statement st1= con.createStatement();
   
         st1.executeUpdate( "UPDATE Tbl2 SET name='"+na+"',Address='"+ad+"',Post_Code="+post+",Telephone="+te+",Email='"+em+"' where NID="+id) ;

           DefaultTableModel model=(DefaultTableModel)jTable_Display_User.getModel();
          
          model.setRowCount(0);
          
          show_user();
          
          
          JOptionPane.showMessageDialog(this, "Data Updated");
          
          
         
         
        }catch(Exception e){ 
          JOptionPane.showMessageDialog(null,e);
        
        }
        
     
        
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBTnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTnActionPerformed
        // TODO add your handling code here:
        
        
         String id =nid.getText();
        String na= name.getText();
        String ad=address.getText();
        String post = pc.getText();
        String te = tele.getText();
        String em=email.getText();
        
        
          try{ 
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        
          
          Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1444;databaseName=DB1;user=TestingUser;password=root");
          
          int row =jTable_Display_User.getSelectedRow();
          
          String value=(jTable_Display_User.getModel().getValueAt(row, 0).toString());
          Statement st2= con.createStatement();
   
         st2.executeUpdate( "DELETE FROM Tbl2 where NID="+id) ;

           DefaultTableModel model=(DefaultTableModel)jTable_Display_User.getModel();
          
          model.setRowCount(0);
          
          show_user();
          
          
          JOptionPane.showMessageDialog(this, "Data Deleted");
          
          
         
         
        }catch(Exception e){ 
          JOptionPane.showMessageDialog(null,e);
        
        }
        
        
        
        
    }//GEN-LAST:event_deleteBTnActionPerformed

    private void npActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npActionPerformed
        // TODO add your handling code here:
        
        Mm obj = new Mm();
        obj.setVisible(true);
    }//GEN-LAST:event_npActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_s.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_s.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_s.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_s.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_s().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JButton deleteBTn;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Display_User;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nid;
    private javax.swing.JButton np;
    private javax.swing.JTextField pc;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField tele;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
