/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logins;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author UNDERTAKER
 */
public class Mm extends javax.swing.JFrame {

    /**
     * Creates new form Mm
     */
    public Mm() {
        initComponents();
         this.setExtendedState(MAXIMIZED_BOTH);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcmbcar = new javax.swing.JComboBox();
        jcmbTrade = new javax.swing.JComboBox();
        jlb1car = new javax.swing.JTextField();
        jlb1Trade = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jcstModified = new javax.swing.JCheckBox();
        jcstStereo = new javax.swing.JCheckBox();
        jcstCustom = new javax.swing.JCheckBox();
        jcstGps = new javax.swing.JCheckBox();
        jcstLeather = new javax.swing.JCheckBox();
        jtxtModified = new javax.swing.JTextField();
        jtxtLeather = new javax.swing.JTextField();
        jtxtCustom = new javax.swing.JTextField();
        jtxtGps = new javax.swing.JTextField();
        jtxtStereo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtReceipt = new javax.swing.JTextArea();
        jbtnReset = new javax.swing.JButton();
        jbtnReceipt = new javax.swing.JButton();
        jbtnTotal = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cars On Sales And Mileage", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Choose a car");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Trade In a Car");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Cost of a car");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Car Mileage");

        jcmbcar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcmbcar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select A Car", "Lamborghini", "Buggati Veyron", "Ferrari", "Audi" }));
        jcmbcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbcarActionPerformed(evt);
            }
        });

        jcmbTrade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcmbTrade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select A Mileage", "100-5000", "5001-20000", "40001-100000" }));
        jcmbTrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbTradeActionPerformed(evt);
            }
        });

        jlb1car.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlb1car.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jlb1car.setText("0");

        jlb1Trade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlb1Trade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jlb1Trade.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(118, 118, 118))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlb1car)
                                .addGap(69, 69, 69)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlb1Trade)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jcmbcar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jcmbTrade, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcmbcar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcmbTrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb1car, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb1Trade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Car Accessories", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jcstModified.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcstModified.setText("Modified($)");
        jcstModified.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcstModifiedActionPerformed(evt);
            }
        });

        jcstStereo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcstStereo.setText("Stereo($)");
        jcstStereo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcstStereoActionPerformed(evt);
            }
        });

        jcstCustom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcstCustom.setText("Customised Detailing($)");
        jcstCustom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcstCustomActionPerformed(evt);
            }
        });

        jcstGps.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcstGps.setText("GPS($)");
        jcstGps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcstGpsActionPerformed(evt);
            }
        });

        jcstLeather.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcstLeather.setText("Leather Interior($)");
        jcstLeather.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcstLeatherActionPerformed(evt);
            }
        });

        jtxtModified.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtModified.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtModified.setText("0");

        jtxtLeather.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtLeather.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtLeather.setText("0");

        jtxtCustom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtCustom.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtCustom.setText("0");

        jtxtGps.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtGps.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtGps.setText("0");
        jtxtGps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtGpsActionPerformed(evt);
            }
        });

        jtxtStereo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtStereo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtStereo.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcstCustom)
                    .addComponent(jcstGps)
                    .addComponent(jcstLeather)
                    .addComponent(jcstModified))
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtStereo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtModified, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtLeather, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtGps, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCustom, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jcstStereo)
                    .addContainerGap(298, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jtxtStereo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcstModified)
                    .addComponent(jtxtModified, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcstLeather)
                    .addComponent(jtxtLeather, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcstCustom)
                    .addComponent(jtxtCustom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcstGps)
                    .addComponent(jtxtGps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(jcstStereo)
                    .addContainerGap(207, Short.MAX_VALUE)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Calculate Total", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Tax");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Subtotal");

        jtxtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Total");

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(jtxtSubTotal)
                    .addComponent(jtxtTotal))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Receipt", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jtxtReceipt.setBackground(new java.awt.Color(204, 204, 255));
        jtxtReceipt.setColumns(20);
        jtxtReceipt.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jtxtReceipt.setRows(5);
        jScrollPane2.setViewportView(jtxtReceipt);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 98, Short.MAX_VALUE))
        );

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jbtnReceipt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnReceipt.setText("Receipt");
        jbtnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReceiptActionPerformed(evt);
            }
        });

        jbtnTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnTotal.setText("Total");
        jbtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalActionPerformed(evt);
            }
        });

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Calculate Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnTotal)
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addComponent(jbtnReceipt)))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1802, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnTotal)
                            .addComponent(jbtnReset)
                            .addComponent(jbtnReceipt))
                        .addGap(44, 44, 44)
                        .addComponent(jbtnExit)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jcstLeatherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcstLeatherActionPerformed
        // TODO add your handling code here:
        
         if(jcstLeather.isSelected()==true){ 
            jtxtLeather.setText("6300");
        jtxtLeather.setEnabled(true);
            
            
            
        }
        else if(jcstLeather.isSelected()==false){ 
        jtxtLeather.setText("0");
            jtxtLeather.setEnabled(false);
        
            
            
            
        }
        
    }//GEN-LAST:event_jcstLeatherActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
     /*   jcmbcar.addItem("Select A Car");
        jcmbcar.addItem("Lamborghini");
        jcmbcar.addItem("Buggati Veyron");
        jcmbcar.addItem("Ferrari");
        jcmbcar.addItem("Audi");
        
        jcmbTrade.addItem("Select A Mileage");
        jcmbTrade.addItem("100-5000");
        jcmbTrade.addItem("5001-20000");
        jcmbTrade.addItem("20001-40000");
        jcmbTrade.addItem("40001-100000");*/
        
        jtxtGps.setEnabled(false);
         jtxtLeather.setEnabled(false);
          jtxtStereo.setEnabled(false);
          jtxtModified.setEnabled(false);
          jtxtCustom.setEnabled(false);
       
        
        
    }//GEN-LAST:event_formWindowActivated

    private void jcmbcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbcarActionPerformed
        // TODO add your handling code here:
        
        if(jcmbcar.getSelectedItem().equals("Lamborghini")){ 
        
        jlb1car.setText("1000000");
        
        
        
        }
        if(jcmbcar.getSelectedItem().equals("Buggati Veyron")){ 
        
        jlb1car.setText("5000000");
        
        
        
        }
        if(jcmbcar.getSelectedItem().equals("Ferrari")){ 
        
        jlb1car.setText("2000000");
        
        
        
        }
        if(jcmbcar.getSelectedItem().equals("Audi")){ 
        
        jlb1car.setText("3000000");
        
        
        
        }
        
    }//GEN-LAST:event_jcmbcarActionPerformed

    private void jcmbTradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbTradeActionPerformed
        // TODO add your handling code here:
        
        
        if(jcmbTrade.getSelectedItem().equals("100-5000")){ 
        
        jlb1Trade.setText("2500");
        
        
        
        }
         if(jcmbTrade.getSelectedItem().equals("5001-20000")){ 
        
        jlb1Trade.setText("15000");
        
        
        
        }
          if(jcmbTrade.getSelectedItem().equals("20001-40000")){ 
        
        jlb1Trade.setText("25000");
        
        
        
        }
           if(jcmbTrade.getSelectedItem().equals("40001-100000")){ 
        
        jlb1Trade.setText("80000");
        
        
        
        }
        
        
        
    }//GEN-LAST:event_jcmbTradeActionPerformed

    private JFrame frame;
    
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        // TODO add your handling code here:
        
        frame = new JFrame("Exit");
        
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit","Vehicle trading system"
        ,JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){ 
        
            System.exit(0);
        
        }
      
        
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        // TODO add your handling code here:
        
        jtxtTax.setText(null);
        jtxtSubTotal.setText(null);
        jtxtTotal.setText(null);
        jlb1car.setText("0");
        jlb1Trade.setText("0");
        jcmbcar.setSelectedItem("Select A Car");
        jcmbTrade.setSelectedItem("Select A Mileage");
        
        
          jtxtGps.setText("0");
         jtxtLeather.setText("0");
          jtxtStereo.setText("0");
          jtxtModified.setText("0");
          jtxtCustom.setText("0");
        
          jtxtGps.setEnabled(false);
         jtxtLeather.setEnabled(false);
          jtxtStereo.setEnabled(false);
          jtxtModified.setEnabled(false);
          jtxtCustom.setEnabled(false);
        
          
          jcstGps.setSelected(false);
         jcstLeather.setSelected(false);
          jcstStereo.setSelected(false);
          jcstModified.setSelected(false);
          jcstCustom.setSelected(false);
          
          
        
        
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jtxtGpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtGpsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtGpsActionPerformed

    private void jcstStereoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcstStereoActionPerformed
        // TODO add your handling code here:
        
        if(jcstStereo.isSelected()==true){ 
            jtxtStereo.setText("450");
        jtxtStereo.setEnabled(true);
            
            
            
        }
        else if(jcstStereo.isSelected()==false){ 
        jtxtStereo.setText("0");
            jtxtStereo.setEnabled(false);
        
            
            
            
        }
        
        
    }//GEN-LAST:event_jcstStereoActionPerformed

    private void jcstModifiedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcstModifiedActionPerformed
        // TODO add your handling code here:
        
         if(jcstModified.isSelected()==true){ 
            jtxtModified.setText("450");
        jtxtModified.setEnabled(true);
            
            
            
        }
        else if(jcstModified.isSelected()==false){ 
        jtxtModified.setText("0");
            jtxtModified.setEnabled(false);
        
            
            
            
        }
        
        
    }//GEN-LAST:event_jcstModifiedActionPerformed

    private void jcstGpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcstGpsActionPerformed
        // TODO add your handling code here:
        
        
         if(jcstGps.isSelected()==true){ 
            jtxtGps.setText("320");
        jtxtGps.setEnabled(true);
            
            
            
        }
        else if(jcstGps.isSelected()==false){ 
        jtxtGps.setText("0");
            jtxtGps.setEnabled(false);
        
            
            
            
        }
        
        
        
        
    }//GEN-LAST:event_jcstGpsActionPerformed

    private void jcstCustomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcstCustomActionPerformed
        // TODO add your handling code here:
        
          if(jcstCustom.isSelected()==true){ 
            jtxtCustom.setText("320");
        jtxtCustom.setEnabled(true);
            
            
            
        }
        else if(jcstCustom.isSelected()==false){ 
        jtxtCustom.setText("0");
            jtxtCustom.setEnabled(false);
        
            
            
            
        }
        
    }//GEN-LAST:event_jcstCustomActionPerformed

    private void jbtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotalActionPerformed
        // TODO add your handling code here:
        
        double[] CarCost= new double[12];
        
        CarCost[0]=Double.parseDouble(jtxtStereo.getText());
        CarCost[1]=Double.parseDouble(jtxtModified.getText());
        CarCost[2]=Double.parseDouble(jtxtLeather.getText());
        CarCost[3]=Double.parseDouble(jtxtCustom.getText());
        CarCost[4]=Double.parseDouble(jtxtGps.getText());
        CarCost[5]=Double.parseDouble(jlb1car.getText());
        CarCost[6]=Double.parseDouble(jlb1Trade.getText());
        
        CarCost[7]=CarCost[0]+CarCost[1]+CarCost[2]+CarCost[3]+CarCost[4]+CarCost[5]+CarCost[6];
        
        CarCost[8]=(CarCost[7] * 0.45)/100;
        
        String Tax = String.format("$%.2f",CarCost[8]);
        
        jtxtTax.setText(Tax);
        
        String SubTotal = String.format("$%.2f",CarCost[7]);
        
        jtxtSubTotal.setText(SubTotal);
        
        
        String Total = String.format("$%.2f",CarCost[7] + CarCost[8]);
        
        jtxtTotal.setText(Total);
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jbtnTotalActionPerformed

    private void jbtnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReceiptActionPerformed
        // TODO add your handling code here:
        
        
        String rTax =(jtxtTax.getText());
        String rSubTotal=(jtxtSubTotal.getText());
        String rTotal=(jtxtTotal.getText());
        String rTradeIn=(jlb1Trade.getText());
        String rSoldCar=(jlb1car.getText());
        
      	jtxtReceipt.append("\tCar Dealer System:\n\n"  
        
        +"\n\nCost of Car:\t\t"+ rSoldCar
        +"\n\nTrade In:\t\t"+ rTradeIn
        +"\n\nTax:\t\t"+ rTax
        +"\n\nSub Total:\t\t"+ rSubTotal
        +"\n\nTotal:\t\t"+ rTotal        
        
        +"\n\n\tThanks For Using Our System\n\n\tTITANIUM CAR INCORPORATED"
        
        
        
        
        
        
        
        
        );
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jbtnReceiptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnReceipt;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnTotal;
    private javax.swing.JComboBox jcmbTrade;
    private javax.swing.JComboBox jcmbcar;
    private javax.swing.JCheckBox jcstCustom;
    private javax.swing.JCheckBox jcstGps;
    private javax.swing.JCheckBox jcstLeather;
    private javax.swing.JCheckBox jcstModified;
    private javax.swing.JCheckBox jcstStereo;
    private javax.swing.JTextField jlb1Trade;
    private javax.swing.JTextField jlb1car;
    private javax.swing.JTextField jtxtCustom;
    private javax.swing.JTextField jtxtGps;
    private javax.swing.JTextField jtxtLeather;
    private javax.swing.JTextField jtxtModified;
    private javax.swing.JTextArea jtxtReceipt;
    private javax.swing.JTextField jtxtStereo;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
